export const books = [
  // --- Fiction Books (7) ---
  {
    id: 1,
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    price: 12.99,
    originalPrice: 19.99,
    discount: 35,
    rating: 4.7,
    reviews: 7854,
    category: "Fiction",
    description: "A comedic science fiction series following the misadventures of the last surviving human, Arthur Dent.",
    pages: 224,
    inStock: true,
    stockCount: 58,
    deliveryTime: "2-3 days",
    images: [
      "https://picsum.photos/seed/hitchhiker1/300/400",
      "https://picsum.photos/seed/hitchhiker2/300/400"
    ],
    isbn: "9780345391803",
    publishedDate: "1979-10-12",
  },
  {
    id: 2,
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 18.50,
    originalPrice: 28.00,
    discount: 34,
    rating: 4.8,
    reviews: 9102,
    category: "Fiction",
    description: "A lone astronaut, the sole survivor of a last-chance mission, must save Earth from an extinction-level threat.",
    pages: 496,
    inStock: true,
    stockCount: 41,
    deliveryTime: "1-2 days",
    images: [
      "https://picsum.photos/seed/hailmary1/300/400",
      "https://picsum.photos/seed/hailmary2/300/400"
    ],
    isbn: "9780593135204",
    publishedDate: "2021-05-04",
  },
  {
    id: 3,
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    price: 15.99,
    originalPrice: 22.99,
    discount: 30,
    rating: 4.6,
    reviews: 6543,
    category: "Fiction",
    description: "The multi-generational story of the Buendía family, whose patriarch founded the town of Macondo.",
    pages: 417,
    inStock: true,
    stockCount: 33,
    deliveryTime: "3-5 days",
    images: [
      "https://picsum.photos/seed/solitude1/300/400",
      "https://picsum.photos/seed/solitude2/300/400"
    ],
    isbn: "9780060883287",
    publishedDate: "1967-05-30",
  },
  {
    id: 4,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 11.99,
    originalPrice: 16.99,
    discount: 29,
    rating: 4.5,
    reviews: 11234,
    category: "Fiction",
    description: "An allegorical novel about a young Andalusian shepherd's journey to the pyramids of Egypt.",
    pages: 208,
    inStock: true,
    stockCount: 72,
    deliveryTime: "2-3 days",
    images: [
      "https://picsum.photos/seed/alchemist1/300/400",
      "https://picsum.photos/seed/alchemist2/300/400"
    ],
    isbn: "9780062315007",
    publishedDate: "1988-01-01",
  },
  {
    id: 5,
    title: "The Martian",
    author: "Andy Weir",
    price: 14.99,
    originalPrice: 21.99,
    discount: 32,
    rating: 4.7,
    reviews: 8976,
    category: "Fiction",
    description: "An astronaut stranded on Mars must use his ingenuity to signal to Earth that he is alive.",
    pages: 384,
    inStock: true,
    stockCount: 45,
    deliveryTime: "2-4 days",
    images: [
        "https://picsum.photos/seed/martian1/300/400",
        "https://picsum.photos/seed/martian2/300/400"
    ],
    isbn: "9780804139021",
    publishedDate: "2014-02-11",
  },
  {
    id: 6,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: 9.99,
    originalPrice: 14.99,
    discount: 33,
    rating: 4.4,
    reviews: 5432,
    category: "Fiction",
    description: "A novel about a young man whose portrait ages while he remains young and beautiful.",
    pages: 254,
    inStock: true,
    stockCount: 61,
    deliveryTime: "3-5 days",
    images: [
        "https://picsum.photos/seed/doriangray1/300/400",
        "https://picsum.photos/seed/doriangray2/300/400"
    ],
    isbn: "9780486278070",
    publishedDate: "1890-07-01",
  },
  {
    id: 7,
    title: "War and Peace",
    author: "Leo Tolstoy",
    price: 22.99,
    originalPrice: 34.99,
    discount: 34,
    rating: 4.3,
    reviews: 3210,
    category: "Fiction",
    description: "An epic novel that intertwines aristocratic families with Napoleon's invasion of Russia.",
    pages: 1225,
    inStock: true,
    stockCount: 22,
    deliveryTime: "4-6 days",
    images: [
        "https://picsum.photos/seed/warpeace1/300/400",
        "https://picsum.photos/seed/warpeace2/300/400"
    ],
    isbn: "9780140447934",
    publishedDate: "1869-01-01",
  },
  // --- Tech Books (7) ---
  {
    id: 8,
    title: "HTML and CSS: Design and Build Websites",
    author: "Jon Duckett",
    price: 35.99,
    originalPrice: 49.99,
    discount: 28,
    rating: 4.8,
    reviews: 3105,
    category: "Tech",
    description: "A visual and highly approachable guide to learning HTML and CSS, perfect for beginners.",
    pages: 512,
    inStock: true,
    stockCount: 55,
    deliveryTime: "1-2 days",
    images: [
      "https://picsum.photos/seed/htmlcss1/300/400",
      "https://picsum.photos/seed/htmlcss2/300/400"
    ],
    isbn: "9781118008188",
    publishedDate: "2011-11-08",
  },
  {
    id: 9,
    title: "JavaScript and JQuery",
    author: "Jon Duckett",
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    rating: 4.7,
    reviews: 2450,
    category: "Tech",
    description: "An interactive and visual guide to front-end development with JavaScript and JQuery.",
    pages: 640,
    inStock: true,
    stockCount: 48,
    deliveryTime: "1-2 days",
    images: [
      "https://picsum.photos/seed/jsjquery1/300/400",
      "https://picsum.photos/seed/jsjquery2/300/400"
    ],
    isbn: "9781118531648",
    publishedDate: "2014-06-02",
  },
  {
    id: 10,
    title: "Eloquent JavaScript, 3rd Edition",
    author: "Marijn Haverbeke",
    price: 31.99,
    originalPrice: 39.99,
    discount: 20,
    rating: 4.7,
    reviews: 1987,
    category: "Tech",
    description: "A modern introduction to programming with an in-depth focus on the JavaScript language.",
    pages: 472,
    inStock: true,
    stockCount: 39,
    deliveryTime: "2-3 days",
    images: [
        "https://picsum.photos/seed/eloquentjs1/300/400",
        "https://picsum.photos/seed/eloquentjs2/300/400"
    ],
    isbn: "9781593279509",
    publishedDate: "2018-12-04",
  },
  {
    id: 11,
    title: "Learning React, 2nd Edition",
    author: "Alex Banks & Eve Porcello",
    price: 45.50,
    originalPrice: 55.99,
    discount: 19,
    rating: 4.6,
    reviews: 1876,
    category: "Tech",
    description: "A hands-on guide to learning the React library for building modern user interfaces.",
    pages: 400,
    inStock: true,
    stockCount: 41,
    deliveryTime: "1-3 days",
    images: [
        "https://picsum.photos/seed/learningreact1/300/400",
        "https://picsum.photos/seed/learningreact2/300/400"
    ],
    isbn: "9781492051724",
    publishedDate: "2020-05-12",
  },
  {
    id: 12,
    title: "CSS: The Definitive Guide",
    author: "Eric A. Meyer & Estelle Weyl",
    price: 48.99,
    originalPrice: 59.99,
    discount: 18,
    rating: 4.7,
    reviews: 987,
    category: "Tech",
    description: "The complete guide to CSS, from basic concepts to advanced techniques for experienced developers.",
    pages: 1064,
    inStock: true,
    stockCount: 25,
    deliveryTime: "2-4 days",
    images: [
        "https://picsum.photos/seed/cssguide1/300/400",
        "https://picsum.photos/seed/cssguide2/300/400"
    ],
    isbn: "9781449393199",
    publishedDate: "2017-11-20",
  },
  {
    id: 13,
    title: "Node.js Design Patterns",
    author: "Mario Casciaro, Luciano Mammino",
    price: 44.99,
    originalPrice: 54.99,
    discount: 18,
    rating: 4.6,
    reviews: 1120,
    category: "Tech",
    description: "Master server-side JavaScript development with this comprehensive guide to Node.js patterns.",
    pages: 584,
    inStock: true,
    stockCount: 31,
    deliveryTime: "2-3 days",
    images: [
        "https://picsum.photos/seed/nodedesign1/300/400",
        "https://picsum.photos/seed/nodedesign2/300/400"
    ],
    isbn: "9781800209770",
    publishedDate: "2020-07-24",
  },
  {
    id: 14,
    title: "The Road to React",
    author: "Robin Wieruch",
    price: 29.99,
    originalPrice: 34.99,
    discount: 14,
    rating: 4.8,
    reviews: 2121,
    category: "Tech",
    description: "A pragmatic and concise guide to learning React.js from the ground up without complex tooling.",
    pages: 242,
    inStock: true,
    stockCount: 47,
    deliveryTime: "1-2 days",
    images: [
        "https://picsum.photos/seed/roadtoreact1/300/400",
        "https://picsum.photos/seed/roadtoreact2/300/400"
    ],
    isbn: "9781720043997",
    publishedDate: "2018-06-05",
  },
  // --- Biography Books (6) ---
  {
    id: 15,
    title: "Shoe Dog: A Memoir by the Creator of Nike",
    author: "Phil Knight",
    price: 17.99,
    originalPrice: 25.00,
    discount: 28,
    rating: 4.8,
    reviews: 8432,
    category: "Biography",
    description: "The memoir of Phil Knight, founder and former CEO of Nike, detailing the early days of the company.",
    pages: 400,
    inStock: true,
    stockCount: 30,
    deliveryTime: "2-3 days",
    images: [
      "https://picsum.photos/seed/shoedog1/300/400",
      "https://picsum.photos/seed/shoedog2/300/400"
    ],
    isbn: "9781501135910",
    publishedDate: "2016-04-26",
  },
  {
    id: 16,
    title: "Into the Wild",
    author: "Jon Krakauer",
    price: 13.50,
    originalPrice: 18.99,
    discount: 29,
    rating: 4.5,
    reviews: 7890,
    category: "Biography",
    description: "The story of Christopher McCandless, a young man who hiked into the Alaskan wilderness.",
    pages: 207,
    inStock: true,
    stockCount: 42,
    deliveryTime: "2-4 days",
    images: [
        "https://picsum.photos/seed/intothewild1/300/400",
        "https://picsum.photos/seed/intothewild2/300/400"
    ],
    isbn: "9780385486804",
    publishedDate: "1996-01-13",
  },
  {
    id: 17,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    price: 16.99,
    originalPrice: 23.99,
    discount: 29,
    rating: 4.6,
    reviews: 6754,
    category: "Biography",
    description: "A landmark volume in science writing, from the Big Bang to black holes.",
    pages: 212,
    inStock: true,
    stockCount: 34,
    deliveryTime: "3-5 days",
    images: [
        "https://picsum.photos/seed/hawking1/300/400",
        "https://picsum.photos/seed/hawking2/300/400"
    ],
    isbn: "9780553380163",
    publishedDate: "1988-04-01",
  },
  {
    id: 18,
    title: "The Man Who Knew Infinity",
    author: "Robert Kanigel",
    price: 15.99,
    originalPrice: 21.99,
    discount: 27,
    rating: 4.7,
    reviews: 1234,
    category: "Biography",
    description: "A life of the genius Srinivasa Ramanujan, a self-taught mathematical prodigy from India.",
    pages: 436,
    inStock: true,
    stockCount: 21,
    deliveryTime: "3-5 days",
    images: [
        "https://picsum.photos/seed/ramanujan1/300/400",
        "https://picsum.photos/seed/ramanujan2/300/400"
    ],
    isbn: "9780671750619",
    publishedDate: "1991-05-01",
  },
  {
    id: 19,
    title: "I Am Malala",
    author: "Malala Yousafzai, Christina Lamb",
    price: 14.50,
    originalPrice: 20.00,
    discount: 28,
    rating: 4.7,
    reviews: 9876,
    category: "Biography",
    description: "The story of the girl who stood up for education and was shot by the Taliban.",
    pages: 320,
    inStock: true,
    stockCount: 38,
    deliveryTime: "2-3 days",
    images: [
        "https://picsum.photos/seed/malala1/300/400",
        "https://picsum.photos/seed/malala2/300/400"
    ],
    isbn: "9780316322409",
    publishedDate: "2013-10-08",
  },
  {
    id: 20,
    title: "Bad Blood",
    author: "John Carreyrou",
    price: 16.99,
    originalPrice: 24.99,
    discount: 32,
    rating: 4.6,
    reviews: 7654,
    category: "Biography",
    description: "The full inside story of the breathtaking rise and shocking collapse of Theranos.",
    pages: 339,
    inStock: true,
    stockCount: 29,
    deliveryTime: "2-4 days",
    images: [
        "https://picsum.photos/seed/badblood1/300/400",
        "https://picsum.photos/seed/badblood2/300/400"
    ],
    isbn: "9781524731656",
    publishedDate: "2018-05-21",
  },
];
export const categories = ["All", "Fiction", "Tech", "Biography"];
export const sortOptions = [
  { value: "title", label: "Title A-Z" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "rating", label: "Rating: High to Low" },
];
